### ISSUE TITLE
[1.20.1]Compatibility with Every Compat(wood types goes wrong)

### ISSUE THREAD

**Issue by BradClc** [0rc1nus/GoodEnding#16]
The wood(cypress and muddy_oak)noteblock does not sound to Bass like all woods should have. And could not be recognize by every compat.
https://github.com/MehVahdJukaar/WoodGood/issues/388#issuecomment-1883539490

**Comment by 0rc1nus** [comment]
Fixed in version 1.0.1

Download link: https://www.curseforge.com/minecraft/mc-mods/good-ending/files
