### ISSUE TITLE
Cypress roots can grow ridiculously long

### ISSUE THREAD

**Issue by Mushroomsock** [0rc1nus/GoodEnding#4]
If a cypress sapling is planted on the edge of a cliff (or any similar location) the roots can end up being crazily long. I guess there should be some maximum length for roots, or maybe a system that checks how long the roots will be and prevents tree growth if they're too long or something along those lines.

![2022-12-18_17 58 57](https://user-images.githubusercontent.com/8728038/208282416-274a6fd0-432b-491d-8245-71e816301312.png)

**Comment by 0rc1nus** [comment]
Fixed in Good Ending 1.0.1
